backend:
  name: git-gateway
  repo: Fonda-Design/fonda-design
  branch: main
  app_id: Ov23liIwDxyXJ5evY2OG
  auth_type: implicit

media_folder: "static/images/uploads" # Folder for uploaded files
public_folder: "/images/uploads" # Folder for accessing uploaded files

collections:
  - name: "walls"
    label: "Walls"
    folder: "content/work/walls"
    media_folder: "content/work/walls"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }

  - name: "illustrations"
    label: "Illustrations"
    folder: "content/work/illustrations"
    media_folder: "content/work/illustrations"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }

  - name: "childrensart"
    label: "Children's Art"
    folder: "content/work/childrensart"
    media_folder: "content/work/childrensart"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }
