backend:
  name: git-gateway
  branch: main # Branch to update
media_folder: "static/images/uploads" # Folder for uploaded files
public_folder: "/images/uploads" # Folder for accessing uploaded files

collections:
  - name: "walls"
    label: "Walls"
    folder: "content/work/walls"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }

  - name: "illustrations"
    label: "Illustrations"
    folder: "content/work/illustrations"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }

  - name: "childrensart"
    label: "Children's Art"
    folder: "content/work/childrensart"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }
